services:

  catalogdb:
    image : mongo

  basketdb:
    image : redis:alpine

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapidocker
    build:
      context: .
      dockerfile: Catalog.Api/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Basket.Api/Dockerfile

volumes:
  mongo_data:   

